### ISSUE TITLE
inconsistent naming of module/repository

### ISSUE THREAD

**Issue by shilbert01** [maxbachmann-magicmirror2/MMM-HideShowMove#1]
When I "git clone" https://github.com/maxbachmann/mmm-snipshideshow.git
the content is checked out into a lowercase directory 'mmm-snipshideshow'

The module (js file inside) is named 'MMM-SnipsHideShow'

In the config file it is advised to configure the module name as 'MMM-SnipsHideShow'

This leads to : loader.js:190 Error on loading script: modules/MMM-SnipsHideShow//MMM-SnipsHideShow.js

renaming the directory to upper-case fixes the issue.

**Comment by maxbachmann** [comment]
I renamed the repository to upper cases. However I will try the whole setup this weekend, to find out what I still need to fix.

**Comment by maxbachmann** [comment]
I still need to check whats exactly happening on MM2 when I have access to my mirror tomorrow. However I already figured out that my snips application still subscribed to a old intent topic, because I initially created it on a different snips account. So now at least the snips part definetly works and sends out a message to the right topic. I will report back when I tested with the mirror
